use crate::{AppState, routes};
use aide::axum::ApiRouter;

pub(super) fn router() -> ApiRouter<AppState> {
    ApiRouter::new()
        .api_route(
            "/api/books/{book_id}/acquisitions",
            aide::axum::routing::post(routes::acquisitions::create)
                .get(routes::acquisitions::list_for_book),
        )
        .api_route(
            "/api/books/{book_id}/acquisitions/http",
            aide::axum::routing::post(routes::acquisitions::create_http),
        )
        .api_route(
            "/api/acquisitions",
            aide::axum::routing::get(routes::acquisitions::list),
        )
        .api_route(
            "/api/acquisitions/{id}",
            aide::axum::routing::get(routes::acquisitions::get),
        )
        .api_route(
            "/api/acquisitions/{id}/delivery",
            aide::axum::routing::put(routes::acquisitions::schedule_delivery),
        )
        .api_route(
            "/api/acquisitions/{id}/inspect",
            aide::axum::routing::post(routes::acquisitions::inspect_files),
        )
        .api_route(
            "/api/acquisitions/{id}/retry",
            aide::axum::routing::post(routes::acquisitions::retry),
        )
        .api_route(
            "/api/acquisitions/{id}/keep-looking",
            aide::axum::routing::post(routes::acquisitions::set_keep_looking),
        )
        .api_route(
            "/api/acquisitions/{id}/cancel",
            aide::axum::routing::post(routes::acquisitions::cancel),
        )
        .api_route(
            "/api/acquisitions/{id}/candidates",
            aide::axum::routing::get(routes::acquisitions::candidates),
        )
        .api_route(
            "/api/acquisitions/{id}/select",
            aide::axum::routing::post(routes::acquisitions::select),
        )
        .api_route(
            "/api/acquisitions/{id}/review",
            aide::axum::routing::get(routes::acquisitions::review),
        )
        .api_route(
            "/api/acquisitions/{id}/review/resolve",
            aide::axum::routing::post(routes::acquisitions::resolve_review),
        )
        .api_route(
            "/api/admin/acquisitions/{id}",
            aide::axum::routing::get(routes::acquisitions::diagnostics),
        )
}
