use crate::{AppState, routes};
use aide::axum::ApiRouter;

pub(super) fn router() -> ApiRouter<AppState> {
    ApiRouter::new()
        .api_route(
            "/api/admin/users",
            aide::axum::routing::get(routes::admin::list_users).post(routes::admin::create_user),
        )
        .api_route(
            "/api/admin/users/{id}",
            aide::axum::routing::put(routes::admin::update_user),
        )
        .api_route(
            "/api/admin/logs",
            aide::axum::routing::get(routes::admin::logs),
        )
        .api_route(
            "/api/admin/maintenance/images",
            aide::axum::routing::get(routes::admin::image_job_status)
                .post(routes::admin::image_job_start),
        )
        .api_route(
            "/api/admin/maintenance/metadata",
            aide::axum::routing::get(routes::admin::metadata_job_status)
                .post(routes::admin::metadata_job_start),
        )
        .api_route(
            "/api/admin/maintenance/metadata/cancel",
            aide::axum::routing::post(routes::admin::metadata_job_cancel),
        )
        .api_route(
            "/api/admin/maintenance/backups",
            aide::axum::routing::get(routes::admin::backup_status),
        )
        .api_route(
            "/api/admin/maintenance/imports",
            aide::axum::routing::get(routes::admin::import_job_status)
                .post(routes::admin::import_job_start),
        )
        .api_route(
            "/api/admin/maintenance/watch",
            aide::axum::routing::get(routes::admin::watch_status),
        )
        .api_route(
            "/api/admin/users/profiles",
            aide::axum::routing::get(routes::admin::user_profiles),
        )
        .api_route(
            "/api/admin/users/{id}/profile-type",
            aide::axum::routing::put(routes::admin::set_profile_type),
        )
        .api_route(
            "/api/admin/users/{id}/restart-onboarding",
            aide::axum::routing::post(routes::admin::restart_onboarding),
        )
        .api_route(
            "/api/admin/children/{id}/readers",
            aide::axum::routing::get(routes::child_readers::list_targets)
                .post(routes::child_readers::create_target),
        )
        .api_route(
            "/api/admin/children/{id}/readers/{target_id}",
            aide::axum::routing::put(routes::child_readers::update_target)
                .delete(routes::child_readers::delete_target),
        )
        .api_route(
            "/api/admin/children/{id}/readers/{target_id}/default",
            aide::axum::routing::post(routes::child_readers::set_default),
        )
        .api_route(
            "/api/admin/children/{id}/reader-tokens",
            aide::axum::routing::get(routes::child_readers::list_tokens)
                .post(routes::child_readers::create_token),
        )
        .api_route(
            "/api/admin/children/{id}/reader-tokens/{token_id}",
            aide::axum::routing::delete(routes::child_readers::revoke_token),
        )
        .api_route(
            "/api/users/{id}/shelf/{book_id}",
            aide::axum::routing::put(routes::household::assign_shelf),
        )
        .api_route(
            "/api/books/{id}/shelf-users",
            aide::axum::routing::get(routes::household::book_shelf_users),
        )
        .api_route(
            "/api/household/members",
            aide::axum::routing::get(routes::household::members),
        )
        .api_route(
            "/api/admin/integrity",
            aide::axum::routing::get(routes::admin::integrity),
        )
        .api_route(
            "/api/admin/library-health",
            aide::axum::routing::get(routes::admin::library_health),
        )
        .api_route(
            "/api/admin/backup",
            aide::axum::routing::get(routes::admin::backup),
        )
        .api_route(
            "/api/admin/books/{id}",
            aide::axum::routing::put(routes::admin::update_book).delete(routes::admin::delete_book),
        )
        .api_route(
            "/api/admin/books/classification-review",
            aide::axum::routing::get(routes::classification::list)
                .post(routes::classification::apply_batch),
        )
        .api_route(
            "/api/admin/series",
            aide::axum::routing::get(routes::admin::list_series).post(routes::admin::create_series),
        )
        .api_route(
            "/api/admin/series/{id}",
            aide::axum::routing::put(routes::admin::update_series),
        )
        .api_route(
            "/api/admin/books/{book_id}/files/{file_id}",
            aide::axum::routing::delete(routes::admin::delete_book_file),
        )
        .api_route(
            "/api/admin/settings",
            aide::axum::routing::get(routes::admin::list_settings),
        )
        .api_route(
            "/api/admin/settings/{key}",
            aide::axum::routing::put(routes::admin::update_setting),
        )
        .api_route(
            "/api/library/scan",
            aide::axum::routing::post(routes::library::start_scan),
        )
        .api_route(
            "/api/library/scan/status",
            aide::axum::routing::get(routes::library::scan_status),
        )
        .api_route(
            "/api/admin/integrations/status",
            aide::axum::routing::get(routes::admin::integration_status),
        )
        .api_route(
            "/api/admin/attention",
            aide::axum::routing::get(routes::admin::attention),
        )
        .api_route(
            "/api/admin/integrations/prowlarr/test",
            aide::axum::routing::post(routes::admin::test_prowlarr),
        )
        .api_route(
            "/api/admin/integrations/torznab/test",
            aide::axum::routing::post(routes::admin::test_torznab),
        )
        .api_route(
            "/api/admin/integrations/newznab/test",
            aide::axum::routing::post(routes::admin::test_newznab),
        )
        .api_route(
            "/api/admin/integrations/sabnzbd/test",
            aide::axum::routing::post(routes::admin::test_sabnzbd),
        )
        .api_route(
            "/api/admin/integrations/qbittorrent/test",
            aide::axum::routing::post(routes::admin::test_qbittorrent),
        )
}
