use crate::{AppState, routes};
use aide::axum::ApiRouter;

pub(super) fn router() -> ApiRouter<AppState> {
    ApiRouter::new()
        .api_route(
            "/api/requests/search",
            aide::axum::routing::get(routes::requests::search),
        )
        .api_route(
            "/api/requests/book",
            aide::axum::routing::get(routes::requests::book),
        )
        .api_route(
            "/api/requests",
            aide::axum::routing::get(routes::requests::list).post(routes::requests::create),
        )
        .api_route(
            "/api/requests/{id}/approve",
            aide::axum::routing::post(routes::requests::approve),
        )
        .api_route(
            "/api/requests/{id}/decline",
            aide::axum::routing::post(routes::requests::decline),
        )
        .api_route(
            "/api/discover",
            aide::axum::routing::get(routes::discover::page),
        )
        .api_route(
            "/api/discover/search",
            aide::axum::routing::get(routes::discover::search),
        )
        .api_route(
            "/api/discover/authors",
            aide::axum::routing::get(routes::library::discover_authors),
        )
        .api_route(
            "/api/discover/authors/photo",
            aide::axum::routing::get(routes::library::discover_author_photo),
        )
        .api_route(
            "/api/discover/authors/ensure",
            aide::axum::routing::post(routes::library::ensure_discover_author),
        )
        .api_route(
            "/api/discover/authors/follow",
            aide::axum::routing::post(routes::library::follow_discover_author),
        )
        .api_route(
            "/api/authors/{id}/catalogue",
            aide::axum::routing::get(routes::library::author_catalogue),
        )
        .api_route(
            "/api/discover/search/page",
            aide::axum::routing::get(routes::discover::search_page),
        )
        .api_route(
            "/api/discover/book",
            aide::axum::routing::get(routes::discover::book),
        )
        .api_route(
            "/api/discover/like",
            aide::axum::routing::post(routes::discover::like),
        )
        .api_route(
            "/api/profile/liked",
            aide::axum::routing::get(routes::auth::liked_books),
        )
        .api_route(
            "/api/profile/stats",
            aide::axum::routing::get(routes::auth::profile_stats),
        )
        .api_route(
            "/api/discover/releases",
            aide::axum::routing::get(routes::discover::releases),
        )
        .api_route(
            "/api/discover/cover/{cover_id}",
            aide::axum::routing::get(routes::discover::cover),
        )
        .api_route(
            "/api/discover/acquisitions",
            aide::axum::routing::post(routes::discover::create_acquisition),
        )
}
