use crate::{AppState, routes};
use aide::axum::ApiRouter;

pub(super) fn router() -> ApiRouter<AppState> {
    ApiRouter::new()
        .api_route(
            "/api/books",
            aide::axum::routing::get(routes::library::list_books),
        )
        .api_route(
            "/api/books/search",
            aide::axum::routing::get(routes::library::search_books),
        )
        .api_route(
            "/api/books/facets",
            aide::axum::routing::get(routes::library::book_facets),
        )
        .api_route(
            "/api/library/comics",
            aide::axum::routing::get(routes::library::comic_shelf),
        )
        .api_route(
            "/api/series/{id}",
            aide::axum::routing::get(routes::library::comic_series),
        )
        .api_route(
            "/api/books/recent",
            aide::axum::routing::get(routes::library::recent_books),
        )
        .api_route(
            "/api/books/continue",
            aide::axum::routing::get(routes::library::continue_reading),
        )
        .api_route(
            "/api/home/rails",
            aide::axum::routing::get(routes::library::home_rails),
        )
        .api_route(
            "/api/home/spotlight",
            aide::axum::routing::get(routes::spotlight::spotlight),
        )
        .api_route(
            "/api/home/updates",
            aide::axum::routing::get(routes::spotlight::updates),
        )
        .api_route(
            "/api/activity/direct",
            aide::axum::routing::get(routes::spotlight::direct_activity),
        )
        .api_route(
            "/api/home/subjects",
            aide::axum::routing::get(routes::library::hidden_subjects),
        )
        .api_route(
            "/api/home/subjects/{normalized}",
            aide::axum::routing::put(routes::library::set_subject_hidden),
        )
        .api_route(
            "/api/books/highlights",
            aide::axum::routing::get(routes::library::highlights),
        )
        .api_route(
            "/api/books/{id}",
            aide::axum::routing::get(routes::library::get_book),
        )
        .api_route(
            "/api/books/{id}/shelf",
            aide::axum::routing::put(routes::library::add_to_shelf)
                .delete(routes::library::remove_from_shelf),
        )
        .api_route(
            "/api/books/{book_id}/completion",
            aide::axum::routing::get(routes::library::book_completion)
                .put(routes::library::set_book_completion),
        )
        .api_route(
            "/api/books/{id}/preference",
            aide::axum::routing::put(routes::library::set_preference),
        )
        .api_route(
            "/api/books/shelf/claim-all",
            aide::axum::routing::post(routes::library::claim_shelf),
        )
        .api_route(
            "/api/books/{id}/related",
            aide::axum::routing::get(routes::library::related_books),
        )
        .api_route(
            "/api/books/{id}/cover",
            aide::axum::routing::get(routes::library::get_cover),
        )
        .api_route(
            "/api/authors/{id}/photo",
            aide::axum::routing::get(routes::library::author_photo),
        )
        .api_route(
            "/api/books/{book_id}/files/{file_id}/download",
            aide::axum::routing::get(routes::library::download_file),
        )
        .api_route(
            "/api/books/{book_id}/files/{file_id}/content",
            aide::axum::routing::get(routes::library::content_file),
        )
        .api_route(
            "/api/books/{book_id}/files/{file_id}/pages",
            aide::axum::routing::get(routes::library::cbz_manifest),
        )
        .api_route(
            "/api/books/{book_id}/files/{file_id}/pages/{page}",
            aide::axum::routing::get(routes::library::cbz_page),
        )
        .api_route(
            "/api/books/{book_id}/files/{file_id}/position",
            aide::axum::routing::get(routes::library::browser_position)
                .put(routes::library::save_browser_position),
        )
        .api_route(
            "/api/books/{book_id}/files/{file_id}/direction",
            aide::axum::routing::put(routes::library::set_reading_direction),
        )
        .api_route(
            "/api/authors",
            aide::axum::routing::get(routes::library::list_authors),
        )
        .api_route(
            "/api/authors/{id}",
            aide::axum::routing::get(routes::library::get_author),
        )
        .api_route(
            "/api/authors/{id}/profile",
            aide::axum::routing::get(routes::library::author_profile),
        )
        .api_route(
            "/api/authors/{id}/automation",
            aide::axum::routing::put(routes::library::set_author_automation),
        )
        .api_route(
            "/api/authors/{id}/follow",
            aide::axum::routing::get(routes::library::follow_state)
                .post(routes::library::follow_author)
                .delete(routes::library::unfollow_author),
        )
}
