export const LANGUAGES: [string, string][] = [
  ['en', 'English'],
  ['sv', 'Swedish'],
  ['no', 'Norwegian'],
  ['da', 'Danish'],
  ['fi', 'Finnish'],
  ['is', 'Icelandic'],
  ['de', 'German'],
  ['fr', 'French'],
  ['es', 'Spanish'],
  ['it', 'Italian'],
  ['pt', 'Portuguese'],
  ['nl', 'Dutch'],
  ['pl', 'Polish'],
  ['cs', 'Czech'],
  ['sk', 'Slovak'],
  ['hu', 'Hungarian'],
  ['ro', 'Romanian'],
  ['bg', 'Bulgarian'],
  ['el', 'Greek'],
  ['tr', 'Turkish'],
  ['ru', 'Russian'],
  ['uk', 'Ukrainian'],
  ['et', 'Estonian'],
  ['lv', 'Latvian'],
  ['lt', 'Lithuanian'],
  ['hr', 'Croatian'],
  ['sr', 'Serbian'],
  ['sl', 'Slovenian'],
  ['ar', 'Arabic'],
  ['he', 'Hebrew'],
  ['fa', 'Persian'],
  ['hi', 'Hindi'],
  ['ja', 'Japanese'],
  ['ko', 'Korean'],
  ['zh', 'Chinese'],
  ['vi', 'Vietnamese'],
  ['th', 'Thai'],
  ['id', 'Indonesian'],
  ['ca', 'Catalan'],
  ['eu', 'Basque'],
]

export function languageLabel(code: string): string {
  return LANGUAGES.find(([value]) => value === code)?.[1] ?? code.toUpperCase()
}
